/* Case study content. Add a new entry to publish another case study.
   Figure helper: F(file, alt, caption, columns out of 12) */
function F(n,alt,cap,w){return{n:n,alt:alt,cap:cap||"",w:w||12}}
window.CASES = [
{
 slug:"ismi", theme:"plum", num:"01", name:"ISMI London", kicker:"Prelaunch social media strategy",
 line:"A nightwear brand about to launch. The plan: build the community first.",
 summary:"A 25 page strategy for a luxury nightwear brand for fuller bust women. Audit, content system, launch roadmap and the numbers worth tracking.",
 meta:[["Brand","ISMI London, luxury nightwear for DD+ women"],["Channels","Instagram and TikTok"],["My work","Strategy: audit, content strategy, launch roadmap, metrics"]],
 cover:"ismi-goal.webp", coverAlt:"Strategy slide with the goal: build a community of fuller bust women who feel understood, because then sales become much easier",
 thumb:"ismi-pillars.webp", thumbAlt:"ISMI London content pillars slide with five weighted pillars",
 blocks:[
 {t:"The project",h:"A launch that starts months before launch day",p:["ISMI London makes luxury nightwear for fuller bust women. The brand was getting ready to launch, with a premium look and a founder who already showed up on camera.","My deliverable was a prelaunch strategy for Instagram and TikTok: what to fix first, what to say, how to build an audience and what to measure. This was strategy work. I did not run the accounts."]},
 {t:"The audit",wide:true,h:"What I found on Instagram and TikTok",p:["I started by looking at what was working, what was missing and where the biggest opportunity sat.","The positioning line, \"Nightwear designed for fuller bust women\", was a good start. It did not yet answer why this brand, why now or why she should care. I recommended leading with how she feels, not just the product spec."],figs:[F("ismi-positioning.webp","Slide comparing ISMI London's current messaging with a recommended emotion led direction","Positioning: from product spec to emotion",12),F("ismi-feed.webp","Feed review slide: shift from a brand talking to women to women talking with the brand","Instagram feed review",6),F("ismi-tiktok.webp","TikTok audit slide listing strengths, opportunities and what is missing","TikTok audit",6)],list:["Instagram: premium branding, a soft luxury look and consistent visuals. The opportunity was to shift from a brand talking to women, to women talking with the brand.","TikTok: the founder was on camera and educational content did well, with 7,000+ views on the top video. What was missing: community, conversation, anticipation and storytelling."]},
 {t:"Strategic direction",wide:true,h:"Community before conversion",p:["The whole plan rests on one idea. If you build a community of women who feel understood, sales get much easier. So every piece of content has one of four jobs: educate, connect, inspire or convert."],figs:[F("ismi-framework.webp","Slide showing the four jobs of content: educate, connect, inspire and convert","The four jobs of every post",12)]},
 {t:"Content strategy",wide:true,h:"Five pillars, weighted by what builds trust fastest",p:["Problem awareness leads at 40%, because the first thing to earn is a reaction like \"finally, someone gets it\". Education and behind the brand follow at 20% each, then community and lifestyle at 10% each.","Each pillar comes with real post ideas, so the strategy can be picked up and used."],figs:[F("ismi-pillars.webp","Five content pillars with percentage weights and goals","The five pillars",12),F("ismi-practice.webp","Pillars in practice: post ideas listed under each pillar","Pillars in practice",12)]},
 {t:"Channel strategy",wide:true,h:"Instagram should feel premium. TikTok should feel authentic.",p:["Instagram focuses on Reels, carousels, beautiful photography and daily Stories. TikTok is for founder videos, storytelling, day in the life and replying to comments with videos. The content mix leans on the founder, because people follow people before they follow brands."],figs:[F("ismi-mix.webp","Content mix: founder 40%, educational 25%, entertainment 15%, product 10%, community 10%","The content mix",12)]},
 {t:"Launch roadmap",wide:true,h:"Launch begins long before launch day",p:["Three months of prelaunch work: build awareness, build trust, build excitement. Then a launch week where every day is an event, and a post launch plan built on customer reviews, user generated content and restocks."],figs:[F("ismi-prelaunch.webp","Three month prelaunch roadmap: awareness, trust and excitement","Prelaunch roadmap",12),F("ismi-launchweek.webp","Launch week plan with a different event each day","Launch week",12)]},
 {t:"Measurement",wide:true,h:"What to track instead of follower count",p:["Followers alone say very little before a product exists. I proposed tracking saves, shares, comments, profile visits and website clicks, then waitlist growth, email sign ups, conversion rate, repeat customers and user generated content.","Growth ideas included working with micro creators (2K to 15K followers), a daily community routine and an email list started before launch."],figs:[F("ismi-metrics.webp","Ten success metrics including saves, shares, waitlist growth and conversion rate","Ten metrics that show real momentum",12)]},
 {t:"Key learning",h:"Before launch, the asset is trust",p:["This was a strategy deliverable, so there are no performance numbers to report. What the work shows is a point of view: for a brand with no product on shelves yet, the job is to build people who care, and let sales follow."]}
 ]
},
{
 slug:"eviesfits", theme:"terra", num:"02", name:"Evie's Fits", kicker:"Brand audit, identity and content strategy",
 line:"A men's footwear brand that sold shoes. It needed to be known for style.",
 summary:"From an Instagram audit to a brand direction, a content strategy and a social plan, built around one idea: be the style educator, not just the seller.",
 meta:[["Client","Evie's Fits, men's footwear and fashion"],["Platforms","Instagram, TikTok, WhatsApp"],["My work","Audit, brand identity, content and social strategy, graphics"]],
 cover:"evies-boards-2.webp", coverAlt:"Evie's Fits brand boards with a brown and cream palette, wood badge logo and styled shoe photography",
 thumb:"evies-boards-2.webp", thumbAlt:"Evie's Fits brand boards in brown and cream",
 blocks:[
 {t:"The situation",h:"Sales came in on irregular days. The page gave people little reason to trust it.",p:["The business goal was clear: move from irregular daily sales to predictable monthly income. The Instagram page was not helping. It had 19 followers and a profile that did not explain what the brand offered."]},
 {t:"The audit",h:"What I noticed",p:["I reviewed the page structure and found the weak spots. The bio did not say what Evie's Fits sold or who it was for. Highlights did not guide a new visitor."],list:["Rewrote the bio so the offer is clear in one read","Organised highlights (New in, Shoes, Wears, Reviews, Delivery) to guide first time visitors","Set a content direction for product posts and reels"]},
 {t:"Before and after",wide:true,h:"Same page, 30 days apart",figs:[F("ef-before.webp","Evie's Fits Instagram profile before the revamp","Before",4),F("ef-after.webp","Evie's Fits Instagram profile after the revamp, with a clear bio and organised highlights","After",4)],stats:[["19 to 200+","followers, organic"],["45 to 300+","profile views in 30 days"]],note:"Figures are from the Instagram profile before and after the revamp. No ads were used."},
 {t:"Brand direction",wide:true,h:"Style educator, not just a seller",p:["I reviewed three Instagram footwear sellers. One had hype and exclusivity but prices out of reach for most people. Another had strong consistency but generic styling and little teaching. That left room for an affordable brand with real personality.","So the positioning became: Nigeria's style educator for quality men's footwear. A secondary position, the wholesale partner that helps resellers win. And an emotional line: confidence through style, accessible to all."],figs:[F("ef-content-positioning.webp","Competitor analysis and positioning strategy slide for Evie's Fits","Competitors and positioning",12)]},
 {t:"Brand identity",wide:true,h:"A palette that says premium without saying expensive",p:["The identity starts with the brand's promise: premium looking fits, expert styling and pocket friendly prices in one place. Values are affordable luxury, quality you can trust and consistency. The voice is confident, friendly and expert.","Brown stands for reliability and warmth. Cream and beige bring balance and sophistication. I built the boards, logo options and graphic style from there."],figs:[F("ef-content-identity.webp","Evie's Fits brand identity slide with values, personality, voice and tone","Brand identity foundations",12),F("evies-boards-1.webp","Evie's Fits identity board with logo options, palette and Look Sharp, Spend Smart board","Identity boards",6),F("evies-boards-3.webp","Evie's Fits board with wood badge logo, palette and styled shoe photography","Logo and palette",6)]},
 {t:"Content strategy",wide:true,h:"Three buyers and four pillars",p:["Three buyer personas shaped the plan. Tunde, an account manager in Lekki who wants to look polished but has no time to shop. Emeka, a small business owner in Abuja looking for a reliable wholesale supplier. And a 30 year old HR manager who likes good style but worries about sizing and picking the wrong colour.","Four pillars carry the content: style inspiration, new arrivals, customer proof, and content for resellers. Each has a goal. Education builds authority, customer spotlights build trust, and product posts drive DMs."],figs:[F("ef-content-persona.webp","Buyer persona slide for Tunde Adeyemi, an account manager in Lekki","A buyer persona",6),F("ef-content-pillars.webp","Content pillars slide with example posts and goals for each pillar","Content pillars",6)]},
 {t:"Social media strategy",wide:true,h:"Goals, KPIs and the content to create",p:["The social plan connects the business goal to three social goals: awareness, engagement and community, and sales. Each has its own KPIs, from follower growth and reach to WhatsApp leads and conversion. The strategy sets out four to five posts a week, Reels and Stories first, and explains why each content type was chosen.","The KPIs are targets set in the strategy, not results."],figs:[F("ef-social-goals.webp","Goals and KPIs slide for Evie's Fits: awareness, engagement and sales","Goals and KPIs",12),F("ef-social-content.webp","Slide listing content types to create and why each was chosen","Content to create, and why",6),F("ef-social-moodboard.webp","Evie's Fits moodboard of product and styling layouts","Moodboard",6)]},
 {t:"Selected execution",h:"Graphics built from the new identity",figs:[F("ef-graphic-products.webp","Evie's Fits product graphic reading Your fit, our priority","Product graphic",6),F("ef-graphic-arrivals.webp","Evie's Fits New Arrivals graphic","New arrivals graphic",6)]},
 {t:"Key learning",h:"Community first, sales second",p:["The strategy closes on one belief: when an audience feels seen, buying follows. The audit made the page clear, the identity made it recognisable, and the content gave people a reason to stay."]}
 ]
},
{
 slug:"opportunityroom", theme:"night", num:"03", name:"The Opportunity Room", kicker:"LinkedIn audit, strategy and brand guide",
 line:"A page full of opportunities. It needed a reason to be remembered.",
 summary:"A LinkedIn audit that moved TOR from posting opportunities to helping young people find, understand and act on them. With a content system, a 30 day calendar and a brand guide.",
 meta:[["Organisation","The Opportunity Room (TOR), Port Harcourt"],["Audience","Students, graduates, young professionals"],["My role","Social media and LinkedIn management"]],
 cover:"tor-framework.webp", coverAlt:"Find, Understand, Act framework slide for The Opportunity Room",
 thumb:"tor-framework.webp", thumbAlt:"TOR Find, Understand, Act framework slide",
 blocks:[
 {t:"The organisation",h:"Jobs, internships, scholarships, fellowships, grants and training",p:["TOR connects young people to opportunities. A volunteer team covers research, content, LinkedIn, community and design. When I audited the page it had around 40 followers and three kinds of recent post: opportunities, recruitment and reposts."]},
 {t:"What I found",wide:true,h:"Not a weak brand. An underdeveloped one.",p:["The idea was clear and the demand was real. But the page read like a noticeboard. Most posts were announcements, like every competitor, and nothing gave people a second reason to follow."],cols:[["Working","A clear proposition. A genuine information gap. Useful post detail on eligibility and deadlines."],["Missing","A recognisable voice. Interpretation of what an opportunity means for the reader. Proof that TOR helps people."]],figs:[F("tor-keepstop.webp","Keep, stop, start slide setting the direction for TOR's LinkedIn page","Keep, stop, start",12)]},
 {t:"Strategic direction",wide:true,h:"Find. Understand. Act.",p:["I reviewed six benchmark pages and drew one lesson from each. The pattern was consistent: the pages that stand out add context. Instead of competing on follower count with a page of 97k, TOR could compete on relevance, clarity and community.","The positioning shift was one sentence."],quote:"If TOR posted it, I know what it means, who it is for, and what to do next.",figs:[F("tor-positioning.webp","Positioning slide: from we share opportunities to we help young people find, understand and act on them","One shift in positioning",6),F("tor-framework.webp","Framework slide: Find, Understand, Act","The framework",6)]},
 {t:"Content strategy",wide:true,h:"Five pillars and seven recognisable series",p:["The feed mix: opportunity discovery 35%, opportunity intelligence 25%, application and career readiness 20%, community and proof 10%, TOR brand 10%. Sixty percent stays on opportunities. The rest gives people reasons to follow TOR itself.","Series make the page predictable: Should You Apply? (who qualifies, who should skip), Before You Apply, Opportunity Roundup, TOR Check In (polls and questions), Room to Grow and Open Doors (real stories)."],figs:[F("tor-pillars.webp","Five pillar content mix for TOR with percentage weights","The five pillars",12)]},
 {t:"Content planning",wide:true,h:"A 30 day LinkedIn calendar",p:["One post a day across eight pillars, from positioning on day one to brand loyalty on day thirty. Roundups land on days 7, 14, 21 and 28, so people learn when to expect a collection. Community posts, including polls, ask the audience what they are applying for and what holds them back.","Fifteen posts depend on the researcher supplying verified opportunities. So the calendar leaves live opportunities out on purpose, and every post is built on checked details."],figs:[F("tor-calendar.webp","30 day LinkedIn calendar at a glance with pillar, format, goal and researcher input for each day","The month at a glance",6),F("tor-days.webp","Day cards from the calendar showing format, goal and call to action for each post","Day cards with format, goal and call to action",6)]},
 {t:"Voice and post system",wide:true,h:"Interpret, don't just announce",p:["The voice comparison says it best. A generic page shouts about an amazing opportunity. TOR says: Before you apply, check these 4 things. Your degree or field, your experience level, your location, the deadline. Same opportunity, more value for the reader, and an honest next step.","I turned that into a post system, so every post is recognisable before the name appears."],figs:[F("tor-voice.webp","Comparison of a generic opportunity post and a TOR style post","Same opportunity, more value",6),F("tor-brand-postsystem.webp","Post templates for opportunity, should you apply and community check in posts","The post system",6)]},
 {t:"Brand guide",wide:true,h:"A brand guide for the page",p:["I also wrote TOR's brand identity guide. Purpose, positioning and promise. Five personality traits: useful, direct, encouraging, young and practical. A navy and gold palette with proportions, typography, voice rules and a LinkedIn page kit with sizes."],figs:[F("tor-brand-colour.webp","TOR brand colour palette: navy leads, gold signals","Colour",6),F("tor-brand-logo.webp","Proposed TOR mark and lockup shown on navy, white and gold","Mark and lockup",6),F("tor-brand-pagekit.webp","TOR LinkedIn page kit with tagline, about line and image sizes","The page, assembled",12)]},
 {t:"Analytics",wide:true,h:"What the page showed",figs:[F("tor-analytics-before.webp","LinkedIn page analytics for TOR, earlier snapshot, last 7 days","Earlier snapshot",6),F("tor-analytics-after.webp","LinkedIn page analytics for TOR, later snapshot, last 7 days","Later snapshot",6)],compare:{head:["Last 7 days","Earlier","Later"],rows:[["Search appearances","32","167"],["New followers","26","54"],["Post impressions","676","1.9k"],["Page visitors","100","41"]]},note:"Both snapshots are LinkedIn's own 7 day page analytics. Page visitors went down, so I report it as it is. The first 30 days were never meant to go viral. They were meant to teach people what TOR is useful for."},
 {t:"Key learning",h:"Compete on clarity",p:["A small page does not win on volume. It wins by being the one that explains. The biggest shift was treating every post as a chance to answer one more question for the reader: why does this matter, who is it for, should I apply, and what do I need?"]}
 ]
},
{
 slug:"abiodun", theme:"cream", num:"04", name:"Abiodun Oluwadare", kicker:"LinkedIn positioning for a Shopify designer",
 line:"A specialist whose profile needed to speak to the people who buy.",
 summary:"Positioning a Shopify website designer and Klaviyo expert on LinkedIn so the right people understand him quickly. With one week of before and after analytics.",
 meta:[["Client","Abiodun Oluwadare, Shopify Website Designer and Klaviyo Expert"],["Audience","Shopify store owners, ecommerce founders, DTC brands"],["My work","Profile restructure, positioning, content approach"]],
 cover:null, heroStats:[["353 to 3,028","post impressions in 7 days"],["880 to 1,080","followers"],["113 to 165","profile viewers (90 days)"]],
 thumb:"abiodun-after.webp", thumbAlt:"Abiodun's LinkedIn analytics after one week",
 blocks:[
 {t:"The situation",h:"Skilled, but hard to read at a glance",p:["Abiodun designs Shopify websites and builds email flows in Klaviyo. His LinkedIn needed to make that clear to people scanning it."]},
 {t:"The audience",h:"The people who hire him, and the people who refer him",p:["His work serves Shopify store owners, ecommerce founders, DTC brands, business owners and marketing decision makers. Referrals matter in that world, so the page also had to make sense to someone recommending him."]},
 {t:"The positioning challenge",h:"Attract buyers, not just attention",p:["More posts would not have fixed it. The question was who the content should attract. Designers talking to other designers get applause. Store owners deciding who to hire need to see that he understands their problem."]},
 {t:"Strategic direction",h:"Written for the buyer",p:["I restructured his profile and content approach around the people who hire and refer him. The page needed to say who he helps and what he does for them, in plain language a store owner would use."],list:["Audience positioning for Shopify and ecommerce buyers","Profile restructure for clarity","Buyer focused content direction","Content ideas that attract the right people, not just more people"]},
 {t:"Analytics",wide:true,h:"One week, before and after",p:["Two LinkedIn analytics screenshots, shown as LinkedIn displays them. The table lists the exact figures from each."],analytics:{before:["abiodun-before.webp","LinkedIn analytics before: 353 post impressions, 880 followers, 113 profile viewers, 16 search appearances"],after:["abiodun-after.webp","LinkedIn analytics after one week: 3,028 post impressions, 1,080 followers, 165 profile viewers, 34 search appearances"],head:["Metric","Before","After","What changed"],rows:[["Post impressions (7 days)","353","3,028","+2,675"],["Followers","880","1,080","+200"],["Profile viewers (90 days)","113","165","+52"],["Search appearances","16","34","+18"]],note:"Figures are taken directly from the two screenshots. LinkedIn's own comparison on the later screenshot shows search appearances flat week on week (0%), so I treat that line as context rather than a win."}},
 {t:"In his words",h:"What changed",quote:"She helped restructure my LinkedIn profile and content approach. The page became clearer, more professional, and easier for people to understand. I also saw an increase in impressions and profile views within a short time.",cite:"Abiodun Oluwadare"},
 {t:"Key learning",h:"Clarity before content",p:["For a specialist, the first job of a profile is to be understood by the right person in a few seconds. Content works harder once that is in place."]}
 ]
},
{
 slug:"serein", theme:"olive", num:"05", name:"Serein Escapes", kicker:"Selected project: content ideas and carousel",
 line:"Travel should feel meaningful, not stressful.",
 summary:"A Reel concept, a carousel concept and a five slide carousel for a curated travel brand, all built around one contrast: the stress of planning against the ease of being looked after.",
 meta:[["Brand","Serein Escapes, curated travel"],["Audience","Young professionals, 25 to 40, creatives and founders"],["My work","Content ideas, Reel concept, five slide carousel design"]],
 cover:null,
 thumb:"serein-5.webp", thumbAlt:"Serein Escapes carousel closing slide",
 blocks:[
 {t:"The brief",h:"Calm, elevated, intentional",p:["The brand sells curated travel focused on rest, discovery and connection. Its personality is warm but never loud, and its key message is that travel should feel meaningful, not stressful. I wrote two original content ideas for Instagram and TikTok, then designed the carousel."]},
 {t:"Content ideas",h:"A Reel for cold audiences, a carousel for warm ones",p:["The Reel opens on the hook: \"You're not tired of traveling. You're tired of planning it.\" It is a 15 to 20 second cinematic sequence that cuts from a stressed person with 27 open tabs to the same person already at a serene destination.","The carousel idea contrasts a trip with an experience, pairing each stressful travel reality with the Serein version. Together they form a small funnel: awareness with the Reel, consideration with the carousel, then a soft call to action."]},
 {t:"The carousel",wide:true,h:"Stop planning. Start living.",p:["Five slides built as Hook, Truth, Value, Contrast, Close. The palette is terracotta, ivory, deep olive and near black, set in Playfair Display and Montserrat."],strip:true,figs:[F("serein-1.webp","Carousel slide 1: Stop Planning, Start Living","Hook",1),F("serein-2.webp","Carousel slide 2: 57 hours is how long the average person spends planning one trip","Truth",1),F("serein-3.webp","Carousel slide 3: Every detail, already handled","Value",1),F("serein-4.webp","Carousel slide 4: regular travel against Serein Escapes","Contrast",1),F("serein-5.webp","Carousel slide 5: Your next escape awaits, with a call to action","Close",1)]},
 {t:"Extra idea",h:"The Serein Files",p:["I also proposed a recurring documentary style Reel series, The Serein Files, so the brand has something people can come back to."]},
 {t:"Takeaway",h:"Sell the feeling, not the itinerary",p:["This was a content project, so there are no performance numbers. It shows how I work from a brand's tone to a concept, from a concept to a hook, and from a hook to a finished design."]}
 ]
}
];
